### ISSUE TITLE
problem with popup list

### ISSUE THREAD

**Issue by JeremyCavanagh** [vindvaki/atom-autocomplete-julia#5]
When using autocomplete with a file tree view on the left side of the screen the list is partially oscured by the treeview even though it is not the focussed window. Also when there is no treeview and the editor window occupies the whole screen the popup list is hard against the left edge of the screen. It would look much better if the left edge of the popup window was indented slightly, preferably to the right of the line number gutter then it would be completely visible even when displaying the file treeview.

**Comment by vindvaki** [comment]
Does this only occur with atom-autocomplete-julia?

**Comment by JeremyCavanagh** [comment]
Hi,
Apologies for my lack of clarity I am only using autocomplete-julia, as I am trying to learn both julia and the atom editor. I haven't tried any other autocomplete varieties. It occurs with a variety of different ui and syntax themes including the atom provided themes. I thought that may have been part of the problem since some commmunity themes don't correctly position the Command Palette (it appears to low and part of it dissappears off the bottom of my screen).

I am working on a MacBook Air running Mac OS X 10.9.5 if that provides more info.

**Comment by JeremyCavanagh** [comment]
To make things a little clearer I have tried to do a couple of screen captures for illustration. I have no idea if this will work, I hope so

![screen shot 2015-11-02 at 21 58 12](https://cloud.githubusercontent.com/assets/5337880/10894155/1a568314-81ad-11e5-886d-a2d4097fa6a9.png)
![screen shot 2015-11-02 at 21 59 32](https://cloud.githubusercontent.com/assets/5337880/10894161/23ce68c6-81ad-11e5-8bf8-1520ddade8e7.png)

**Comment by vindvaki** [comment]
Thanks for the clarification. I'll take a look at it.

**Comment by JonnyCBB** [comment]
I have this problem as well

**Comment by vindvaki** [comment]
Hi guys, I just tried the package out on OS X and couldn't reproduce it there either. In any case, I'm not really working on it, so I've unpublished it
