### ISSUE TITLE
Julia subprocess consumes 100% of CPU and doesn't close after Atom closes

### ISSUE THREAD

**Issue by mindbound** [vindvaki/atom-autocomplete-julia#6]
Pretty much what it says on the title. Happens randomly, around 30% of the time.

**Comment by r-chris** [comment]
same here - this package seems very unstable. I realized after my computer started working slowly that it actually had spawned 2 julia processes running at 100% and I had to manually kill them off. Processes should definitely be child processes and terminate when Atom shuts down.

**Comment by vindvaki** [comment]
Indeed. I've unpublished the package because I'm not really working on it and it's clearly not in a usable state
