### ISSUE TITLE
Autocomplete is only available for a few minutes after opening

### ISSUE THREAD

**Issue by ararslan** [vindvaki/atom-autocomplete-julia#7]
Whenever I open a Julia file with Atom, I'm able to use autocomplete in all of its glory, but only for a couple minutes. After that none of the menus or anything pop up. It appears the package just kind of goes idle or something.

Information in case it matters:
- autocomplete-julia 0.1.0
- Atom 1.3.2
- Julia 0.4.2
- Mac OS X 10.10

Let me know what other information would be helpful.

**Comment by JonnyCBB** [comment]
I have exactly the same problem.

**Comment by ivirshup** [comment]
@JonnyCBB I'm having the same problem, what provider did you switch to?

**Comment by JonnyCBB** [comment]
@ivirshup I'm using JunoLab's [CodeTools](https://github.com/JunoLab/CodeTools.jl). This package is a part of the [current Julia IDE](http://www.juliabloggers.com/julia-ide-work-in-atom/) effort for Atom. The setup for it can be found [here](https://github.com/JunoLab/atom-julia-client/tree/master/manual). Although I've only used the [dev setup](https://github.com/JunoLab/atom-julia-client/tree/master/docs) which works perfectly.

**Comment by vindvaki** [comment]
@ivirshup Honestly, CodeTools is probably a better solution

**Comment by ivirshup** [comment]
I'll check that out, thanks for the recommendations.
