### ISSUE TITLE
issue with julia + atom

### ISSUE THREAD

**Issue by alexfrieden** [vindvaki/atom-autocomplete-julia#9]
installed atom + julia 0.4.5 today.  Getting the following from this plugin

<img width="522" alt="screen shot 2016-03-31 at 9 39 34 am" src="https://cloud.githubusercontent.com/assets/1154496/14177513/a3cc8e08-f724-11e5-8e2c-8f19e1b62816.png">

**Comment by vindvaki** [comment]
Yes, I've unpublished the package because it's not really in a usable state anymore
